/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gWyyZSPyyL5
 */

import { Footer } from "@/app/footer/page"
import { Navbar } from "@/app/navbar/page"
import { JSX, SVGProps } from "react"


export function About() {
  return (
    <>
      <Navbar/>
      <div className="bg-gray-50/90 py-10 lg:py-16">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">About Us</h1>
            <p className="text-gray-600 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We're redefining real estate with a fresh perspective. Welcome to our world.
            </p>
          </div>
        </div>
      </div>
      <section className="py-10 lg:py-16">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <img
            alt="Image"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
            height="500"
            src="https://images.unsplash.com/photo-1523532200165-fbffcc61172a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx2aXN1YWwtc2VhcmNofDR8fHxlbnwwfHx8fHw%3D"
            width="900"
          />
          <div className="flex flex-col gap-4 text-center md:gap-10 lg:text-left">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Our Story</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">A New Era of Real Estate</h2>
            </div>
            <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Founded on the principles of innovation and customer-centricity, our company is committed to transforming
              the real estate industry. We believe in leveraging technology to simplify the homebuying process and
              creating a seamless experience for our clients.
            </p>
          </div>
        </div>
      </section>
      <section className="bg-gray-100 py-10 lg:py-16">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <div className="space-y-4 text-center lg:space-y-0 lg:text-left">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Our Core Values</h2>
            <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              At the heart of our company are the values that guide our actions and decisions. We are dedicated to
              upholding these principles in everything we do.
            </p>
          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
            <div className="flex items-start gap-4">
              <CheckCircleIcon className="h-6 w-6 flex-shrink-0 text-gray-500" />
              <div className="space-y-2">
                <h3 className="text-lg font-semibold tracking-wide">Customer First</h3>
                <p className="text-sm text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
                  We prioritize the needs of our customers and are committed to delivering exceptional service.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <CheckCircleIcon className="h-6 w-6 flex-shrink-0 text-gray-500" />
              <div className="space-y-2">
                <h3 className="text-lg font-semibold tracking-wide">Innovation</h3>
                <p className="text-sm text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
                  We embrace creativity and are always seeking new ways to improve the real estate experience through
                  innovation.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <CheckCircleIcon className="h-6 w-6 flex-shrink-0 text-gray-500" />
              <div className="space-y-2">
                <h3 className="text-lg font-semibold tracking-wide">Integrity</h3>
                <p className="text-sm text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
                  We operate with honesty and transparency, earning the trust of our clients and partners.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <CheckCircleIcon className="h-6 w-6 flex-shrink-0 text-gray-500" />
              <div className="space-y-2">
                <h3 className="text-lg font-semibold tracking-wide">Collaboration</h3>
                <p className="text-sm text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
                  We believe in the power of teamwork and work together to achieve the best results for our clients.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-10 lg:py-16">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <img
            alt="Image"
            className="mx-auto aspect-square overflow-hidden rounded-full object-cover object-center"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="space-y-4 text-center lg:text-left">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Leadership</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet Our Team</h2>
            </div>
            <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our team is composed of dedicated professionals who are passionate about real estate and are committed to
              providing our clients with the best possible experience.
            </p>
          </div>
        </div>
      </section>
      <section className="py-12 lg:py-16">
        <div className="container px-4 md:px-6">
          <div className="grid items-start gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">Jane Smith</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">CEO</p>
              </div>
              <div className="space-y-4 text-base leading-loose md:text-lg md:leading-loose lg:text-base lg:leading-loose xl:text-lg xl:leading-loose">
                <p>
                  Jane is a visionary leader with over 20 years of experience in the real estate industry. She is
                  dedicated to driving innovation and ensuring that our company remains at the forefront of the market.
                </p>
                <p>
                  Under her guidance, we have expanded our services and established ourselves as a trusted name in real
                  estate.
                </p>
              </div>
            </div>
            <div className="grid items-start gap-4 text-center md:grid-cols-2 md:text-left lg:text-center lg:items-center lg:gap-2 xl:gap-4">
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center md:order-last lg:mx-0 lg:mr-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center lg:mx-0 lg:ml-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 lg:py-16">
        <div className="container px-4 md:px-6">
          <div className="grid items-start gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">John Doe</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">CFO</p>
              </div>
              <div className="space-y-4 text-base leading-loose md:text-lg md:leading-loose lg:text-base lg:leading-loose xl:text-lg xl:leading-loose">
                <p>
                  John is a financial expert with a passion for real estate. He oversees our company's finances and
                  ensures that we maintain a strong financial position.
                </p>
                <p>His strategic approach has allowed us to make sound investments and achieve sustainable growth.</p>
              </div>
            </div>
            <div className="grid items-start gap-4 text-center md:grid-cols-2 md:text-left lg:text-center lg:items-center lg:gap-2 xl:gap-4">
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center md:order-last lg:mx-0 lg:mr-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center lg:mx-0 lg:ml-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 lg:py-16">
        <div className="container px-4 md:px-6">
          <div className="grid items-start gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">Sarah Johnson</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Head of Sales</p>
              </div>
              <div className="space-y-4 text-base leading-loose md:text-lg md:leading-loose lg:text-base lg:leading-loose xl:text-lg xl:leading-loose">
                <p>
                  Sarah is a dynamic leader who is passionate about delivering results. She leads our sales team with
                  enthusiasm and is dedicated to ensuring that our clients find their dream homes.
                </p>
                <p>
                  Her in-depth knowledge of the real estate market and her customer-centric approach have made her a
                  valuable asset to our team.
                </p>
              </div>
            </div>
            <div className="grid items-start gap-4 text-center md:grid-cols-2 md:text-left lg:text-center lg:items-center lg:gap-2 xl:gap-4">
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center md:order-last lg:mx-0 lg:mr-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center lg:mx-0 lg:ml-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 lg:py-16">
        <div className="container px-4 md:px-6">
          <div className="grid items-start gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">Michael Lee</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Head of Marketing</p>
              </div>
              <div className="space-y-4 text-base leading-loose md:text-lg md:leading-loose lg:text-base lg:leading-loose xl:text-lg xl:leading-loose">
                <p>
                  Michael is a creative professional with a flair for marketing. He leads our marketing efforts with
                  innovative strategies that capture the attention of our target audience.
                </p>
                <p>
                  His expertise in digital marketing has helped us reach new heights and position our brand as a leader
                  in the industry.
                </p>
              </div>
            </div>
            <div className="grid items-start gap-4 text-center md:grid-cols-2 md:text-left lg:text-center lg:items-center lg:gap-2 xl:gap-4">
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center md:order-last lg:mx-0 lg:mr-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
              <img
                alt="Image"
                className="mx-auto rounded-full object-cover object-center lg:mx-0 lg:ml-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width="400"
              />
            </div>
          </div>
        </div>
      </section>
      <Footer/>
    </>
  )
}


function CheckCircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
