/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vml2hKjwDni
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Navbar } from "@/app/navbar/page"
import { Footer } from "@/app/footer/page"
import Map from "@/components/component/Map";

export function Contactus() {
  return (
    <>
    <Navbar />
    <section key="1" className="w-full py-12">
  <div className="container grid gap-6 lg:grid-cols-2 lg:gap-12 xl:gap-16">
    {/* Add the image to the left */}
    <div className="rounded-xl overflow-hidden aspect-square lg:aspect-none">
      {/*<Image src="https://images.unsplash.com/photo-1708873776992-d78034cec91c?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Not Found Image" width={500} height={400} />*/}
      <Map address={{ lat: 21.195491, lng: 81.292878 }} />
    </div>

    <div className="flex flex-col justify-center space-y-4">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold">Contact us</h2>
        <p className="text-gray-500 dark:text-gray-400">
          We&apos;re here to help. Fill out the form below and we&apos;ll be in touch as soon as possible.
        </p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">First name</Label>
            <Input id="first-name" placeholder="Enter your first name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Last name</Label>
            <Input id="last-name" placeholder="Enter your last name" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="Enter your email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="subject">Subject</Label>
          <Input id="subject" placeholder="Enter the subject" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="message">Message</Label>
          <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
        </div>
        <Button>Send message</Button>
      </div>
    </div>
  </div>
</section>
    <Footer />
    </>
  )
}
