/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5NMVK97FfHf
 */
import Link from "next/link"
//import { Input } from "@/components/ui/input"
//import { Button } from "@/components/ui/button"
//import { JSX, SVGProps } from "react"
import { MountainIcon } from "lucide-react"
import { Navbar } from "@/app/navbar/page"
import { Footer } from "@/app/footer/page"
import { DrawerDialogDemo } from "@/app/contact-button/page"

export function Feature() {
  return (
    <><Navbar />
      <div className="bg-gray-50/90 border-t border-b border-gray-200 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
        <div className="container px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 items-center py-6 text-center md:text-left">
            <div className="flex flex-col justify-center space-y-2">
              <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Schedule a Tour</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Speak with an agent to learn more about our properties.
              </p>
            </div>
              <DrawerDialogDemo/>
          </div>
        </div>
      </div>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container grid gap-12 px-4 md:px-6 lg:grid-cols-2 xl:gap-20">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Explore the Possibilities
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Your Dream Home Awaits</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Discover the perfect blend of comfort and style with our collection of exquisite homes. Whether you're
                looking for a cozy apartment in the heart of the city or a spacious house in the suburbs, we have the
                ideal option for you.
              </p>
            </div>
          </div>
          <div className="mx-auto grid gap-6 rounded-xl aspect-video overflow-hidden items-center justify-center">
            <img
              alt="Image"
              className="object-cover object-center rounded-xl"
              height="450"
              src="https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2075&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              style={{
                aspectRatio: "800/450",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16 xl:gap-20">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Modern Living
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Seamless Integration</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Embrace the future of smart homes with our integrated technology solutions. Control your environment
                with ease, from adjusting the lighting to setting the perfect temperature, all at the touch of a button.
                Experience convenience and comfort like never before.
              </p>
            </div>
          </div>
          <div className="grid gap-6 rounded-xl aspect-video overflow-hidden items-center justify-center">
            <img
              alt="Image"
              className="object-cover object-center rounded-xl"
              height="450"
              src="https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              style={{
                aspectRatio: "800/450",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16 xl:gap-20">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Urban Oasis</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Serene Retreat</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Escape the hustle and bustle of the city in your own private sanctuary. Our rooftop gardens provide a
                tranquil space to relax and recharge, surrounded by lush greenery and breathtaking views. Whether you're
                enjoying a morning yoga session or hosting an intimate gathering, our urban oasis offers the perfect
                blend of natural beauty and contemporary elegance.
              </p>
            </div>
          </div>
          <div className="grid gap-6 rounded-xl aspect-video overflow-hidden items-center justify-center">
            <img
              alt="Image"
              className="object-cover object-center rounded-xl"
              height="450"
              src="https://images.unsplash.com/photo-1519302959554-a75be0afc82a?q=80&w=1784&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              style={{
                aspectRatio: "800/450",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16 xl:gap-20">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Elevated Experience
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Luxury Redefined</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Indulge in the epitome of sophistication with our meticulously designed interiors. Every detail has been
                curated to create an atmosphere of understated elegance, from the exquisite finishes to the thoughtfully
                crafted layouts. Experience the pinnacle of luxury living and immerse yourself in a world of comfort and
                style.
              </p>
            </div>
          </div>
          <div className="grid gap-6 rounded-xl aspect-video overflow-hidden items-center justify-center">
            <img
              alt="Image"
              className="object-cover object-center rounded-xl"
              height="450"
              src="https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              style={{
                aspectRatio: "800/450",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16 xl:gap-20">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Coastal Living
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Beachfront Bliss</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Embrace the laid-back charm of coastal living with our stunning beachfront properties. Wake up to the
                sound of waves and bask in the golden sunshine from your own piece of paradise. Whether you're a water
                sports enthusiast or simply love the ocean views, our beachfront homes offer the perfect combination of
                luxury and relaxation.
              </p>
            </div>
          </div>
          <div className="grid gap-6 rounded-xl aspect-video overflow-hidden items-center justify-center">
            <img
              alt="Image"
              className="object-cover object-center rounded-xl"
              height="450"
              src="https://images.unsplash.com/photo-1605549339992-83721992836e?q=80&w=1787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              style={{
                aspectRatio: "800/450",
                objectFit: "cover",
              }}
              width="800"
            />
          </div>
        </div>
      </section>
      <div className="bg-gray-50/90 border-t border-gray-200 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
        <div className="container grid gap-12 px-4 py-12 md:px-6 md:grid-cols-2 items-center lg:gap-16 xl:gap-20">
          <div className="space-y-2 text-center md:text-left">
            <h3 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Schedule a Tour</h3>
            <p className="text-gray-500 dark:text-gray-400">Speak with an agent to learn more about our properties.</p>
          </div>
          <DrawerDialogDemo />
        </div>
      </div>
      <Footer />
    </>
  )
}
