/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jYyBkdc5NyY
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
//import Link from "next/link"
//import {MountainIcon, } from "lucide-react"
import { Navbar } from "@/app/navbar/page"
//import { DrawerDialogDemo } from "@/app/contact-button/page"

export function Login() {
  return (
    <>
    <Navbar/>
    <div className="flex flex-col min-h-screen items-center justify-center space-y-4 p-4" style={{ marginTop: '-60px' }}>
  <div className="w-full max-w-sm space-y-2">
    <div className="text-center space-y-2">
      <h1 className="text-3xl font-bold">Welcome</h1>
      <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account.</p>
    </div>
    <div className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" placeholder="m@example.com" required type="email" />
      </div>
      <div className="space-y-2">
        <Label htmlFor="password">Password</Label>
        <Input id="password" required type="password" />
      </div>
      <Button className="w-full">Sign in</Button>
    </div>
  </div>
</div>
</>
  )
}
