/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/alL8IKAVouU
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import { Navbar } from "@/app/navbar/page"
import { Footer } from "@/app/footer/page"
import { Contactus } from "@/app/contact-page/page"
import {Typer} from "@/app/typewritter/page"
import Spl from "@/components/component/spline"

export function Page() {
  return (
    <div key="1" className="flex flex-col min-h-[100dvh]">
      <Navbar/>
      <Typer/>
      {/*<Spl/>*/}
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-t">
          <div className="container space-y-10 px-4 sm:px-6 md:space-y-16 lg:px-10">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Luxury Homes
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Discover the Epitome of Elegance</h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Immerse yourself in the allure of our luxury homes, where sophistication meets comfort.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 px-4 lg:grid-cols-2 lg:gap-12">
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="310"
                  src="https://images.unsplash.com/photo-1613545325278-f24b0cae1224?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width="550"
                />
              </div>
              <div className="grid gap-4">
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">The Essence of Opulence</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Each of our luxury homes is a masterpiece, offering unparalleled beauty and tranquility.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Exquisite Architecture</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Marvel at the attention to detail in every corner, from grand entrances to serene gardens.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Modern Amenities</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Experience the perfect blend of tradition and innovation with state-of-the-art features.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container space-y-10 px-4 sm:px-6 md:space-y-16 lg:px-10">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Commercial Properties
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Prime Locations for Success</h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Elevate your business with our exceptional commercial properties, strategically designed for growth.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 px-4 lg:grid-cols-2 lg:gap-12">
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="310"
                  src="https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width="550"
                />
              </div>
              <div className="grid gap-4">
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Strategic Advantage</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our commercial properties are located in the heart of thriving business districts, offering
                    unparalleled visibility and accessibility.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Customization</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Tailor the space to meet your company's unique needs with our flexible design options and modern
                    architecture.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Investment Potential</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Secure your future with a commercial property that offers long-term value and growth opportunities.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-10 px-4 sm:px-6 md:space-y-16 lg:px-10">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Investment Opportunities
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Unlock the Potential of Prosperity</h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Embrace the possibilities with our curated selection of investment opportunities, designed to generate
                  wealth and success.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 px-4 lg:grid-cols-2 lg:gap-12">
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="310"
                  src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width="550"
                />
              </div>
              <div className="grid gap-4">
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Diverse Portfolios</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Explore a range of investment options, from residential properties to commercial ventures, curated
                    to deliver value.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Expert Guidance</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Our team of advisors is dedicated to helping you make informed decisions and identify opportunities
                    for growth.
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-bold">Wealth Creation</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Invest with confidence, knowing that your assets are positioned to appreciate and generate long-term
                    returns.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Experience the workflow the best frontend teams love.
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Let your team focus on shipping features instead of managing infrastructure with automated CI/CD.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-2">
                <Input className="mx-auto max-w-lg" placeholder="Enter your email" type="email" />
                <Button className="mx-auto w-[200px]" type="submit">
                  Sign Up
                </Button>
              </form>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Sign up to get notified when we launch.
                <Link className="underline underline-offset-2" href="#">
                  Terms & Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
      </main>
      
      <Contactus/>
      <Footer />
    </div>
  )
}


function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
