/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kas5TCXq5Mr
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { JSX, SVGProps } from "react"
import { Navbar } from "@/app/navbar/page"
import { Footer } from "@/app/footer/page"
//style={{ backgroundImage: `url(${https://plus.unsplash.com/premium_photo-1661954372617-15780178eb2e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fGx1eHVyeSUyMGhvdXNlfGVufDB8MHwwfHx8MA%3D%3D})`, backgroundSize: 'cover', backgroundPosition: 'center' }

export function Pricing() {
  return (
    <>
    <Navbar/>
      <div className="py-6 lg:py-12">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <div className="grid gap-10">
            <Card>
              <CardHeader className="pb-20">
                <CardTitle>House</CardTitle>
                <CardDescription>Beautiful homes for every lifestyle.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                <HomeIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $250,000</h3>
                  <Badge variant="default">New</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Browse our listings of homes in your area.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium translate-y-3" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-0" />
                  View Homes
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="pb-20">
                <CardTitle>Land</CardTitle>
                <CardDescription>Build your dreams from the ground up.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                <TreesIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $100,000</h3>
                  <Badge variant="default">Acres</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Find the perfect plot for your vision.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium translate-y-3" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-0" />
                  View Land
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="pb-20">
                <CardTitle>Projects</CardTitle>
                <CardDescription>Invest in the future with our development projects.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                <LayoutGridIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $500,000</h3>
                  <Badge variant="default">Investment</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Discover exciting opportunities for growth.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium translate-y-3" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-0" />
                  View Projects
                </Link>
              </CardFooter>
            </Card>
          </div>
        </div>
      </div>
      {/*<div className="bg-gray-50 py-6 lg:py-12">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Find Your Perfect Property</h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Browse our exclusive listings of homes, land, and major projects.
            </p>
          </div>
        </div>
      </div>
      <div className="py-6 lg:py-12">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <div className="grid gap-2">
            <Card>
              <CardHeader className="pb-0">
                <CardTitle>House</CardTitle>
                <CardDescription>Beautiful homes for every lifestyle.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                <HomeIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $250,000</h3>
                  <Badge variant="default">New</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Browse our listings of homes in your area.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-2" />
                  View Homes
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="pb-0">
                <CardTitle>Land</CardTitle>
                <CardDescription>Build your dreams from the ground up.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                <TreesIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $100,000</h3>
                  <Badge variant="default">Acres</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Find the perfect plot for your vision.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-2" />
                  View Land
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader className="pb-0">
                <CardTitle>Projects</CardTitle>
                <CardDescription>Invest in the future with our development projects.</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                <LayoutGridIcon className="mx-auto h-10 w-10" />
                <div className="flex items-center justify-center space-x-2">
                  <h3 className="font-bold">Starting at $500,000</h3>
                  <Badge variant="default">Investment</Badge>
                </div>
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  Discover exciting opportunities for growth.
                </p>
              </CardContent>
              <CardFooter className="border-t">
                <Link className="inline-flex items-center space-x-2 text-sm font-medium" href="#">
                  <ArrowRightIcon className="h-4 w-4 translate-x-2" />
                  View Projects
                </Link>
              </CardFooter>
            </Card>
          </div>
        </div>
      </div>*/}
      <Footer/>
    </>
  )
}


function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function ArrowRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function TreesIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 10v.2A3 3 0 0 1 8.9 16v0H5v0h0a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z" />
      <path d="M7 16v6" />
      <path d="M13 19v3" />
      <path d="M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5" />
    </svg>
  )
}


function LayoutGridIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  )
}
